### ISSUE TITLE
Newline as an option

### ISSUE THREAD

**Issue by ThomDietrich** [wooorm/retext-sentence-spacing#5]
Hey woorm!

You've referred me here from https://github.com/why-jay/remark-lint-sentence-newline/issues/25 - however the plugin only supports single and double space. Would you be able to add newline as an option?

Many thanks!!

**Comment by wooorm** [comment]
Correct. This plugin doesn’t support a newline between sentences. Would you be interested in creating a PR for that?

**Comment by wooorm** [comment]
@ThomDietrich Ping!

**Comment by ThomDietrich** [comment]
Hey @wooorm, thanks for the reminder and the invite. I'm not an experienced js developer, by all means. I'm on it. Do think it would be needed to also generate a warning with two lines and the setting `preffered: 1` ?

**Comment by wooorm** [comment]
Alright! Let’s talk over on GH-6!
